# Generated by Django 4.2.7 on 2023-11-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0003_master_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='service',
        ),
    ]
