# Generated by Django 4.2.7 on 2023-11-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barberapp', '0005_appointment_comments_appointment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
